[project]
name = "family-cashflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numbers-parser>=4.14.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
